[
    {
        "isRoute": true,
        "lat": 43.665278,
        "lng": 7.215,
        "name": "NICE/COTE DAZUR",
        "info": "Departure airport",
        "icao": "LFMN",
        "runway_size": "9700ft",
        "elevation": "12ft",
        "trasition": "5000ft",
        "icon_url": "./img/departing.png",
        "icon_center_x": 13,
        "icon_center_y": 13
    },
    {
        "isRoute": true,
        "lat": 48.723333,
        "lng": 2.379444,
        "name": "ORLY",
        "info": "Arrival airport",
        "icao": "LFPO",
        "runway_size": "11900ft",
        "elevation": "291ft",
        "trasition": "5000ft",
        "icon_url": "./img/arrival.png",
        "icon_center_x": 13,
        "icon_center_y": 13
    },
    {
        "isRoute": false,
        "lat": 48.110278,
        "lng": 16.569722,
        "name": "SCHWECHAT",
        "info": "LOWW",
        "icao": "LOWW",
        "runway_size": "11800ft",
        "elevation": "600ft",
        "trasition": "10000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 47.458056,
        "lng": 8.548056,
        "name": "ZURICH",
        "info": "LSZH",
        "icao": "LSZH",
        "runway_size": "12100ft",
        "elevation": "1417ft",
        "trasition": "7000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 43.665278,
        "lng": 7.215,
        "name": "NICE/COTE DAZUR",
        "info": "LFMN",
        "icao": "LFMN",
        "runway_size": "9700ft",
        "elevation": "12ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 41.900833,
        "lng": 2.760556,
        "name": "GIRONA",
        "info": "LEGE",
        "icao": "LEGE",
        "runway_size": "7800ft",
        "elevation": "469ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 38.872778,
        "lng": 1.373056,
        "name": "IBIZA",
        "info": "LEIB",
        "icao": "LEIB",
        "runway_size": "9100ft",
        "elevation": "24ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 42.524444,
        "lng": 8.793056,
        "name": "ST CATHERINE",
        "info": "LFKC",
        "icao": "LFKC",
        "runway_size": "7500ft",
        "elevation": "210ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 52.559686,
        "lng": 13.287711,
        "name": "TEGEL",
        "info": "EDDT",
        "icao": "EDDT",
        "runway_size": "9900ft",
        "elevation": "122ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 46.993056,
        "lng": 15.439167,
        "name": "GRAZ",
        "info": "LOWG",
        "icao": "LOWG",
        "runway_size": "9800ft",
        "elevation": "1120ft",
        "trasition": "10000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 48.689878,
        "lng": 9.221964,
        "name": "STUTTGART",
        "info": "EDDS",
        "icao": "EDDS",
        "runway_size": "10900ft",
        "elevation": "1276ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 52.308056,
        "lng": 4.764167,
        "name": "SCHIPHOL",
        "info": "EHAM",
        "icao": "EHAM",
        "runway_size": "12400ft",
        "elevation": "-11ft",
        "trasition": "3000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 51.885,
        "lng": 0.235,
        "name": "STANSTED",
        "info": "EGSS",
        "icao": "EGSS",
        "runway_size": "10000ft",
        "elevation": "348ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 53.421389,
        "lng": -6.27,
        "name": "DUBLIN INTL",
        "info": "EIDW",
        "icao": "EIDW",
        "runway_size": "8600ft",
        "elevation": "242ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 49.623333,
        "lng": 6.204444,
        "name": "LUXEMBOURG",
        "info": "ELLX",
        "icao": "ELLX",
        "runway_size": "13100ft",
        "elevation": "1234ft",
        "trasition": "4500ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 53.630389,
        "lng": 9.988228,
        "name": "HAMBURG",
        "info": "EDDH",
        "icao": "EDDH",
        "runway_size": "12000ft",
        "elevation": "53ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 49.945819,
        "lng": 7.261078,
        "name": "FRANKFURT-HAHN",
        "info": "EDFH",
        "icao": "EDFH",
        "runway_size": "12400ft",
        "elevation": "1649ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 52.165833,
        "lng": 20.967222,
        "name": "CHOPIN",
        "info": "EPWA",
        "icao": "EPWA",
        "runway_size": "12100ft",
        "elevation": "362ft",
        "trasition": "6500ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 43.635,
        "lng": 1.367778,
        "name": "BLAGNAC",
        "info": "LFBO",
        "icao": "LFBO",
        "runway_size": "11400ft",
        "elevation": "499ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 39.489444,
        "lng": -0.481667,
        "name": "MANISES",
        "info": "LEVC",
        "icao": "LEVC",
        "runway_size": "10500ft",
        "elevation": "240ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 46.238333,
        "lng": 6.109444,
        "name": "GENEVA",
        "info": "LSGG",
        "icao": "LSGG",
        "runway_size": "12700ft",
        "elevation": "1411ft",
        "trasition": "7000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 50.033306,
        "lng": 8.570456,
        "name": "FRANKFURT/MAIN",
        "info": "EDDF",
        "icao": "EDDF",
        "runway_size": "13100ft",
        "elevation": "364ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 51.280925,
        "lng": 6.757311,
        "name": "DUESSELDORF",
        "info": "EDDL",
        "icao": "EDDL",
        "runway_size": "9800ft",
        "elevation": "147ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 48.353783,
        "lng": 11.786086,
        "name": "MUNICH",
        "info": "EDDM",
        "icao": "EDDM",
        "runway_size": "13100ft",
        "elevation": "1487ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 45.63,
        "lng": 8.723056,
        "name": "MALPENSA",
        "info": "LIMC",
        "icao": "LIMC",
        "runway_size": "12800ft",
        "elevation": "768ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 41.296944,
        "lng": 2.078333,
        "name": "EL PRAT",
        "info": "LEBL",
        "icao": "LEBL",
        "runway_size": "10900ft",
        "elevation": "14ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": -3.775833,
        "lng": -38.532222,
        "name": "PINTO MARTINS INTL",
        "info": "SBFZ",
        "icao": "SBFZ",
        "runway_size": "8300ft",
        "elevation": "82ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": -8.126389,
        "lng": -34.922778,
        "name": "GUARARAPES-GILBERTO ",
        "info": "SBRF",
        "icao": "SBRF",
        "runway_size": "9800ft",
        "elevation": "33ft",
        "trasition": "4000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": -12.908611,
        "lng": -38.3225,
        "name": "DEP. L. E. MAGALHAES",
        "info": "SBSV",
        "icao": "SBSV",
        "runway_size": "9800ft",
        "elevation": "66ft",
        "trasition": "7000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": -19.624444,
        "lng": -43.971944,
        "name": "TANCREDO NEVES INTL",
        "info": "SBCF",
        "icao": "SBCF",
        "runway_size": "9800ft",
        "elevation": "2713ft",
        "trasition": "8000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": -22.91,
        "lng": -43.1625,
        "name": "SANTOS DUMONT",
        "info": "SBRJ",
        "icao": "SBRJ",
        "runway_size": "4300ft",
        "elevation": "10ft",
        "trasition": "7000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 51.148056,
        "lng": -0.190278,
        "name": "GATWICK",
        "info": "EGKK",
        "icao": "EGKK",
        "runway_size": "10800ft",
        "elevation": "203ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 55.509444,
        "lng": -4.594444,
        "name": "PRESTWICK",
        "info": "EGPK",
        "icao": "EGPK",
        "runway_size": "9700ft",
        "elevation": "65ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 53.353889,
        "lng": -2.275,
        "name": "MANCHESTER",
        "info": "EGCC",
        "icao": "EGCC",
        "runway_size": "10000ft",
        "elevation": "257ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 41.800278,
        "lng": 12.238889,
        "name": "FIUMICINO",
        "info": "LIRF",
        "icao": "LIRF",
        "runway_size": "12800ft",
        "elevation": "14ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 48.235278,
        "lng": 14.188056,
        "name": "LINZ",
        "info": "LOWL",
        "icao": "LOWL",
        "runway_size": "9800ft",
        "elevation": "980ft",
        "trasition": "10000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 40.214167,
        "lng": 0.073611,
        "name": "CASTELLON",
        "info": "LECH",
        "icao": "LECH",
        "runway_size": "8800ft",
        "elevation": "1181ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 51.423992,
        "lng": 12.236383,
        "name": "LEIPZIG-HALLE",
        "info": "EDDP",
        "icao": "EDDP",
        "runway_size": "11800ft",
        "elevation": "470ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 44.828611,
        "lng": -0.715278,
        "name": "MERIGNAC",
        "info": "LFBD",
        "icao": "LFBD",
        "runway_size": "10100ft",
        "elevation": "166ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 39.601944,
        "lng": 19.912222,
        "name": "IOANNIS KAPODISTRIAS",
        "info": "LGKR",
        "icao": "LGKR",
        "runway_size": "7700ft",
        "elevation": "6ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 47.671317,
        "lng": 9.511486,
        "name": "FRIEDRICHSHAFEN",
        "info": "EDNY",
        "icao": "EDNY",
        "runway_size": "7700ft",
        "elevation": "1368ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 51.396667,
        "lng": -3.343333,
        "name": "CARDIFF",
        "info": "EGFF",
        "icao": "EGFF",
        "runway_size": "7700ft",
        "elevation": "220ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 38.282222,
        "lng": -0.558056,
        "name": "ALICANTE-ELCHE",
        "info": "LEAL",
        "icao": "LEAL",
        "runway_size": "9800ft",
        "elevation": "142ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 38.774167,
        "lng": -9.134167,
        "name": "LISBON",
        "info": "LPPT",
        "icao": "LPPT",
        "runway_size": "12100ft",
        "elevation": "374ft",
        "trasition": "4000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 43.583333,
        "lng": 3.961389,
        "name": "MONTPELLIER/MEDITERR",
        "info": "LFMT",
        "icao": "LFMT",
        "runway_size": "8500ft",
        "elevation": "17ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 54.6575,
        "lng": -6.215833,
        "name": "ALDERGROVE",
        "info": "EGAA",
        "icao": "EGAA",
        "runway_size": "9100ft",
        "elevation": "268ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 39.551667,
        "lng": 2.738889,
        "name": "PALMA DE MALLORCA",
        "info": "LEPA",
        "icao": "LEPA",
        "runway_size": "10700ft",
        "elevation": "27ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 44.413333,
        "lng": 8.8375,
        "name": "SESTRI",
        "info": "LIMJ",
        "icao": "LIMJ",
        "runway_size": "9500ft",
        "elevation": "13ft",
        "trasition": "7000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 51.134344,
        "lng": 13.768,
        "name": "DRESDEN",
        "info": "EDDC",
        "icao": "EDDC",
        "runway_size": "9300ft",
        "elevation": "754ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 55.617917,
        "lng": 12.655972,
        "name": "KASTRUP",
        "info": "EKCH",
        "icao": "EKCH",
        "runway_size": "11800ft",
        "elevation": "17ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 51.4775,
        "lng": -0.461389,
        "name": "HEATHROW",
        "info": "EGLL",
        "icao": "EGLL",
        "runway_size": "12800ft",
        "elevation": "83ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 36.675,
        "lng": -4.499167,
        "name": "COSTA DEL SOL",
        "info": "LEMG",
        "icao": "LEMG",
        "runway_size": "10400ft",
        "elevation": "52ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 50.563333,
        "lng": 3.086944,
        "name": "LESQUIN",
        "info": "LFQQ",
        "icao": "LFQQ",
        "runway_size": "9200ft",
        "elevation": "157ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 47.59,
        "lng": 7.529167,
        "name": "BASLE-MULHOUSE",
        "info": "LFSB",
        "icao": "LFSB",
        "runway_size": "12700ft",
        "elevation": "885ft",
        "trasition": "7000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 43.682778,
        "lng": 10.395556,
        "name": "SAN GIUSTO",
        "info": "LIRP",
        "icao": "LIRP",
        "runway_size": "9800ft",
        "elevation": "6ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 50.901389,
        "lng": 4.484444,
        "name": "BRUSSELS NATIONAL",
        "info": "EBBR",
        "icao": "EBBR",
        "runway_size": "11900ft",
        "elevation": "184ft",
        "trasition": "4500ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": -23.626111,
        "lng": -46.656389,
        "name": "CONGONHAS",
        "info": "SBSP",
        "icao": "SBSP",
        "runway_size": "6300ft",
        "elevation": "2631ft",
        "trasition": "8000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 55.95,
        "lng": -3.3725,
        "name": "EDINBURGH",
        "info": "EGPH",
        "icao": "EGPH",
        "runway_size": "8300ft",
        "elevation": "136ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 47.260278,
        "lng": 11.343889,
        "name": "INNSBRUCK",
        "info": "LOWI",
        "icao": "LOWI",
        "runway_size": "6500ft",
        "elevation": "1907ft",
        "trasition": "10000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 60.202778,
        "lng": 11.083889,
        "name": "GARDERMOEN",
        "info": "ENGM",
        "icao": "ENGM",
        "runway_size": "11800ft",
        "elevation": "681ft",
        "trasition": "7000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 53.0474,
        "lng": 8.786747,
        "name": "BREMEN",
        "info": "EDDW",
        "icao": "EDDW",
        "runway_size": "6600ft",
        "elevation": "14ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 47.156944,
        "lng": -1.607778,
        "name": "NANTES/ATLANTIQUE",
        "info": "LFRS",
        "icao": "LFRS",
        "runway_size": "9500ft",
        "elevation": "90ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 32.694167,
        "lng": -16.778056,
        "name": "MADEIRA",
        "info": "LPMA",
        "icao": "LPMA",
        "runway_size": "9100ft",
        "elevation": "191ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 28.429389,
        "lng": -81.309,
        "name": "ORLANDO INTL",
        "info": "KMCO",
        "icao": "KMCO",
        "runway_size": "12000ft",
        "elevation": "96ft",
        "trasition": "18000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 51.382778,
        "lng": -2.719167,
        "name": "BRISTOL",
        "info": "EGGD",
        "icao": "EGGD",
        "runway_size": "6500ft",
        "elevation": "622ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 51.614089,
        "lng": 8.616317,
        "name": "PADERBORN/LIPPSTADT",
        "info": "EDLP",
        "icao": "EDLP",
        "runway_size": "7100ft",
        "elevation": "699ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 33.364167,
        "lng": -7.581667,
        "name": "MOHAMMED V INTL",
        "info": "GMMN",
        "icao": "GMMN",
        "runway_size": "12200ft",
        "elevation": "656ft",
        "trasition": "4000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 36.151175,
        "lng": -5.34975,
        "name": "GIBRALTAR",
        "info": "LXGB",
        "icao": "LXGB",
        "runway_size": "5800ft",
        "elevation": "12ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 40.472222,
        "lng": -3.560833,
        "name": "ADOLFO SUAREZ MADRID",
        "info": "LEMD",
        "icao": "LEMD",
        "runway_size": "13700ft",
        "elevation": "1998ft",
        "trasition": "13000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 43.040833,
        "lng": 144.193056,
        "name": "KUSHIRO",
        "info": "RJCK",
        "icao": "RJCK",
        "runway_size": "8200ft",
        "elevation": "311ft",
        "trasition": "14000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 34.784444,
        "lng": 135.439167,
        "name": "OSAKA INTL",
        "info": "RJOO",
        "icao": "RJOO",
        "runway_size": "9800ft",
        "elevation": "39ft",
        "trasition": "14000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 32.916944,
        "lng": 129.913611,
        "name": "NAGASAKI",
        "info": "RJFU",
        "icao": "RJFU",
        "runway_size": "9800ft",
        "elevation": "8ft",
        "trasition": "14000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 35.553333,
        "lng": 139.781111,
        "name": "TOKYO HANEDA INTL",
        "info": "RJTT",
        "icao": "RJTT",
        "runway_size": "11000ft",
        "elevation": "21ft",
        "trasition": "14000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 34.434167,
        "lng": 135.232778,
        "name": "KANSAI INTL",
        "info": "RJBB",
        "icao": "RJBB",
        "runway_size": "13100ft",
        "elevation": "17ft",
        "trasition": "14000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": -23.435556,
        "lng": -46.473056,
        "name": "GUARULHOS-GOV ANDRE ",
        "info": "SBGR",
        "icao": "SBGR",
        "runway_size": "12100ft",
        "elevation": "2461ft",
        "trasition": "8000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": -22.81,
        "lng": -43.250556,
        "name": "GALEAO-ANTONIO C JOB",
        "info": "SBGL",
        "icao": "SBGL",
        "runway_size": "13100ft",
        "elevation": "28ft",
        "trasition": "7000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 34.895667,
        "lng": -82.218858,
        "name": "GREENVILLE SPARTANBU",
        "info": "KGSP",
        "icao": "KGSP",
        "runway_size": "11000ft",
        "elevation": "964ft",
        "trasition": "18000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 36.894611,
        "lng": -76.201222,
        "name": "NORFOLK INTL",
        "info": "KORF",
        "icao": "KORF",
        "runway_size": "9000ft",
        "elevation": "27ft",
        "trasition": "18000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 50.865917,
        "lng": 7.142744,
        "name": "COLOGNE-BONN",
        "info": "EDDK",
        "icao": "EDDK",
        "runway_size": "12500ft",
        "elevation": "302ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 18.570781,
        "lng": -68.366186,
        "name": "PUNTA CANA INTL",
        "info": "MDPC",
        "icao": "MDPC",
        "runway_size": "10100ft",
        "elevation": "47ft",
        "trasition": "17000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 48.723333,
        "lng": 2.379444,
        "name": "ORLY",
        "info": "LFPO",
        "icao": "LFPO",
        "runway_size": "11900ft",
        "elevation": "291ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 55.038056,
        "lng": -1.689722,
        "name": "NEWCASTLE",
        "info": "EGNT",
        "icao": "EGNT",
        "runway_size": "7600ft",
        "elevation": "266ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 50.077778,
        "lng": 19.784722,
        "name": "BALICE",
        "info": "EPKK",
        "icao": "EPKK",
        "runway_size": "8300ft",
        "elevation": "791ft",
        "trasition": "6500ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 37.014444,
        "lng": -7.965833,
        "name": "FARO",
        "info": "LPFR",
        "icao": "LPFR",
        "runway_size": "8100ft",
        "elevation": "24ft",
        "trasition": "4000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 53.333611,
        "lng": -2.849722,
        "name": "LIVERPOOL",
        "info": "EGGP",
        "icao": "EGGP",
        "runway_size": "7400ft",
        "elevation": "81ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 47.794444,
        "lng": 13.003333,
        "name": "SALZBURG",
        "info": "LOWS",
        "icao": "LOWS",
        "runway_size": "9000ft",
        "elevation": "1411ft",
        "trasition": "10000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 51.874722,
        "lng": -0.368333,
        "name": "LUTON",
        "info": "EGGW",
        "icao": "EGGW",
        "runway_size": "7000ft",
        "elevation": "526ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 18.040928,
        "lng": -63.108958,
        "name": "PRINCESS JULIANA INT",
        "info": "TNCM",
        "icao": "TNCM",
        "runway_size": "7500ft",
        "elevation": "14ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 18.4394,
        "lng": -66.002136,
        "name": "LUIS MUNOZ MARIN INT",
        "info": "TJSJ",
        "icao": "TJSJ",
        "runway_size": "10400ft",
        "elevation": "9ft",
        "trasition": "18000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 52.460214,
        "lng": 9.683522,
        "name": "HANNOVER",
        "info": "EDDV",
        "icao": "EDDV",
        "runway_size": "10400ft",
        "elevation": "183ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 40.898611,
        "lng": 9.517778,
        "name": "COSTA SMERALDA",
        "info": "LIEO",
        "icao": "LIEO",
        "runway_size": "8000ft",
        "elevation": "37ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 37.804002,
        "lng": -1.131192,
        "name": "MURCIA",
        "info": "LEMI",
        "icao": "LEMI",
        "runway_size": "9843ft",
        "elevation": "633ft",
        "trasition": "4000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 48.447222,
        "lng": -4.421667,
        "name": "BRETAGNE",
        "info": "LFRB",
        "icao": "LFRB",
        "runway_size": "10100ft",
        "elevation": "325ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 42.55,
        "lng": 9.484722,
        "name": "PORETTA",
        "info": "LFKB",
        "icao": "LFKB",
        "runway_size": "8200ft",
        "elevation": "26ft",
        "trasition": "6200ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": -5.908333,
        "lng": -35.249167,
        "name": "AUGUSTO SEVERO",
        "info": "SBNT",
        "icao": "SBNT",
        "runway_size": "8500ft",
        "elevation": "171ft",
        "trasition": "4000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": -29.993889,
        "lng": -51.171111,
        "name": "SALGADO FILHO INTL",
        "info": "SBPA",
        "icao": "SBPA",
        "runway_size": "7400ft",
        "elevation": "12ft",
        "trasition": "4000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": -23.330278,
        "lng": -51.136667,
        "name": "GOVERNADOR JOSE RICH",
        "info": "SBLO",
        "icao": "SBLO",
        "runway_size": "6800ft",
        "elevation": "1867ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": -25.531667,
        "lng": -49.176111,
        "name": "AFONSO PENA INTL",
        "info": "SBCT",
        "icao": "SBCT",
        "runway_size": "7200ft",
        "elevation": "2989ft",
        "trasition": "7000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": -5.768889,
        "lng": -35.366389,
        "name": "GOV ALUIZIO ALVES IN",
        "info": "SBSG",
        "icao": "SBSG",
        "runway_size": "9800ft",
        "elevation": "273ft",
        "trasition": "0ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 45.786111,
        "lng": 3.1625,
        "name": "CLERMONT-FERRAND/AUV",
        "info": "LFLC",
        "icao": "LFLC",
        "runway_size": "9800ft",
        "elevation": "1092ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 51.570278,
        "lng": 0.693333,
        "name": "SOUTHEND",
        "info": "EGMC",
        "icao": "EGMC",
        "runway_size": "6000ft",
        "elevation": "55ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 48.541944,
        "lng": 7.634444,
        "name": "ENTZHEIM",
        "info": "LFST",
        "icao": "LFST",
        "runway_size": "7800ft",
        "elevation": "505ft",
        "trasition": "7000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 57.66,
        "lng": 12.291111,
        "name": "LANDVETTER",
        "info": "ESGG",
        "icao": "ESGG",
        "runway_size": "10800ft",
        "elevation": "507ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": -27.670278,
        "lng": -48.5525,
        "name": "HERCILIO LUZ INTL",
        "info": "SBFL",
        "icao": "SBFL",
        "runway_size": "7500ft",
        "elevation": "17ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 45.396389,
        "lng": 10.887778,
        "name": "VILLAFRANCA",
        "info": "LIPX",
        "icao": "LIPX",
        "runway_size": "10000ft",
        "elevation": "240ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 52.453889,
        "lng": -1.748056,
        "name": "BIRMINGHAM",
        "info": "EGBB",
        "icao": "EGBB",
        "runway_size": "10000ft",
        "elevation": "339ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 55.871944,
        "lng": -4.433056,
        "name": "GLASGOW",
        "info": "EGPF",
        "icao": "EGPF",
        "runway_size": "8700ft",
        "elevation": "26ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": -2.586944,
        "lng": -44.236111,
        "name": "MARECHAL CUNHA MACHA",
        "info": "SBSL",
        "icao": "SBSL",
        "runway_size": "7800ft",
        "elevation": "178ft",
        "trasition": "3000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": -1.384722,
        "lng": -48.478889,
        "name": "VAL DE CANS/JULIO CE",
        "info": "SBBE",
        "icao": "SBBE",
        "runway_size": "9100ft",
        "elevation": "56ft",
        "trasition": "2000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": -3.250833,
        "lng": -52.252222,
        "name": "ALTAMIRA",
        "info": "SBHT",
        "icao": "SBHT",
        "runway_size": "6500ft",
        "elevation": "368ft",
        "trasition": "3000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": -3.041111,
        "lng": -60.050556,
        "name": "EDUARDO GOMES INTL",
        "info": "SBEG",
        "icao": "SBEG",
        "runway_size": "8800ft",
        "elevation": "262ft",
        "trasition": "4000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 45.742931,
        "lng": 16.068778,
        "name": "PLESO",
        "info": "LDZA",
        "icao": "LDZA",
        "runway_size": "10600ft",
        "elevation": "353ft",
        "trasition": "9500ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 51.240278,
        "lng": 22.713611,
        "name": "LUBLIN",
        "info": "EPLB",
        "icao": "EPLB",
        "runway_size": "8200ft",
        "elevation": "633ft",
        "trasition": "6500ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 45.505278,
        "lng": 12.351944,
        "name": "TESSERA",
        "info": "LIPZ",
        "icao": "LIPZ",
        "runway_size": "10800ft",
        "elevation": "7ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 46.224444,
        "lng": 14.456111,
        "name": "BRNIK",
        "info": "LJLJ",
        "icao": "LJLJ",
        "runway_size": "10800ft",
        "elevation": "1273ft",
        "trasition": "10500ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 52.362247,
        "lng": 13.500672,
        "name": "SCHOENEFELD",
        "info": "EDDB",
        "icao": "EDDB",
        "runway_size": "13100ft",
        "elevation": "157ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 45.449444,
        "lng": 9.278333,
        "name": "LINATE",
        "info": "LIML",
        "icao": "LIML",
        "runway_size": "8000ft",
        "elevation": "353ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 39.1775,
        "lng": 23.503611,
        "name": "ALEXANDROS PAPADIAMA",
        "info": "LGSK",
        "icao": "LGSK",
        "runway_size": "5300ft",
        "elevation": "54ft",
        "trasition": "4000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 38.181944,
        "lng": 13.099444,
        "name": "PUNTA RAISI",
        "info": "LICJ",
        "icao": "LICJ",
        "runway_size": "10900ft",
        "elevation": "65ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 49.4987,
        "lng": 11.078008,
        "name": "NUERNBERG",
        "info": "EDDN",
        "icao": "EDDN",
        "runway_size": "8800ft",
        "elevation": "1046ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 42.896389,
        "lng": -8.415278,
        "name": "SANTIAGO",
        "info": "LEST",
        "icao": "LEST",
        "runway_size": "10400ft",
        "elevation": "1213ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 41.235556,
        "lng": -8.678056,
        "name": "FRANCISCO SA CARNEIR",
        "info": "LPPR",
        "icao": "LPPR",
        "runway_size": "11400ft",
        "elevation": "227ft",
        "trasition": "4000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 43.301111,
        "lng": -2.910556,
        "name": "BILBAO",
        "info": "LEBB",
        "icao": "LEBB",
        "runway_size": "8500ft",
        "elevation": "136ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 44.368056,
        "lng": -1.132222,
        "name": "PARENTIS",
        "info": "LFBS",
        "icao": "LFBS",
        "runway_size": "2600ft",
        "elevation": "100ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 28.044444,
        "lng": -16.5725,
        "name": "REINA SOFIA",
        "info": "GCTS",
        "icao": "GCTS",
        "runway_size": "10400ft",
        "elevation": "209ft",
        "trasition": "6000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 53.866111,
        "lng": -1.660833,
        "name": "LEEDS BRADFORD",
        "info": "EGNM",
        "icao": "EGNM",
        "runway_size": "7300ft",
        "elevation": "681ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 33.6367,
        "lng": -84.427864,
        "name": "HARTSFIELD - JACKSON",
        "info": "KATL",
        "icao": "KATL",
        "runway_size": "12300ft",
        "elevation": "1026ft",
        "trasition": "18000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 35.765278,
        "lng": 140.385556,
        "name": "NARITA INTL",
        "info": "RJAA",
        "icao": "RJAA",
        "runway_size": "13100ft",
        "elevation": "135ft",
        "trasition": "14000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 41.504111,
        "lng": -74.104833,
        "name": "STEWART INTL",
        "info": "KSWF",
        "icao": "KSWF",
        "runway_size": "11800ft",
        "elevation": "491ft",
        "trasition": "18000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 43.097222,
        "lng": 6.146111,
        "name": "LE PALYVESTRE NAVY",
        "info": "LFTH",
        "icao": "LFTH",
        "runway_size": "6900ft",
        "elevation": "13ft",
        "trasition": "5000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": -16.629722,
        "lng": -49.226667,
        "name": "SANTA GENOVEVA",
        "info": "SBGO",
        "icao": "SBGO",
        "runway_size": "8200ft",
        "elevation": "2451ft",
        "trasition": "7000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    },
    {
        "isRoute": false,
        "lat": 2.841389,
        "lng": -60.692222,
        "name": "ATLAS BRAZIL CANTANH",
        "info": "SBBV",
        "icao": "SBBV",
        "runway_size": "8800ft",
        "elevation": "276ft",
        "trasition": "4000ft",
        "icon_url": "./img/favorite.png",
        "icon_center_x": 8,
        "icon_center_y": 8
    }
]